### ISSUE TITLE
Update to conform to github UI change

### ISSUE THREAD

**Issue by zaki** [nikolaiwarner/Looks-Good-To-Me#11]
Github just changed their UI layout, which unfortunately broke the LGTM extension, so it needs to be updated.

**Comment by nikolaiwarner** [comment]
I published version 1.8.0 to the Chrome store today. Are you running this version yet?

**Comment by zaki** [comment]
Yes. I think GH layout changed only a couple hours ago.

Individual pull request discussion page is alright, only the pull request list page that stopped working:

![lgtm_new_ui](https://f.cloud.github.com/assets/21428/342405/491b0c9c-9da3-11e2-949e-a850cbb22dda.png)

**Comment by nikolaiwarner** [comment]
Ok! I see what you mean.

They changed the title from a h3 to h4. That's all! lol

Fixed and pushed to Chrome store!
